# Generated by Django 4.2.7 on 2025-11-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='postgres_lob_oid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='storage_type',
            field=models.CharField(choices=[('cloudinary', 'Cloudinary'), ('postgres_lob', 'PostgreSQL Large Object'), ('local_file', 'Local File System')], default='cloudinary', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='postgres_lob_oid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_bytes_written',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='use_postgres_lob',
            field=models.BooleanField(default=False),
        ),
    ]
